### ISSUE TITLE
Organizations must have an @id

### ISSUE THREAD

**Issue by thill-odi** [upshot-oa/opendata#6]
Review of validator output (https://validator.openactive.io/?url=https%3A%2F%2Fapp.upshot.org.uk%2Fapi%2Fv0%2Fopenactive%2Fv1.0%2F&version=2.0&validationMode=RPDEFeed) indicates that the required `@id` value is not being supplied to `Organizations`.

**Comment by domfennell** [comment]
To add to this, the information included in the `organizer` object appears to be, at present, limited - only `name` seems to be included. Most of our customers require more comprehensive organiser information to guarantee a good UX for their users, e.g. URL, logo, description, email address, phone number, social media links, etc.

**Comment by zerolab** [comment]
Thanks both. I am now looking into this and other raised issues.

I would like to point out that https://developer.openactive.io/data-model/types/organization lists `@id` under "Optional properties", so there is a bit of disconnect between the developer docs and the validator

**Comment by domfennell** [comment]
Hi @zerolab, thanks for looking at this and the other issues.

You're right - there is a disconnect. I believe this was due to an update to accommodate the introduction of virtual sessions at the start of lockdown last year. This is seen from the [Virtual Events](https://developer.openactive.io/publishing-data/virtual-events#sessionseries-headlineevent-courseinstance-and-event) page of the Developer Docs, which notes that "`@id` is required to give each organizer a globally unique identifier in the form of a URL".

Thanks for flagging this. Seems like everything needs aligning and updating for clarity!

**Comment by zerolab** [comment]
`@id` added and pointing to the organisation's public calendar. e.g. https://app.upshot.org.uk/calendar/sessions/c00d87c5/ (from https://app.upshot.org.uk/api/v0/openactive/v1.0/?afterTimestamp=1580120345509644&afterId=3b03823070e8323b)
